### ISSUE TITLE
Landing - First Step

### ISSUE THREAD

**Issue by TorinAsakura** [Nikitabkv/Nikitabkv.github.io#8]
### Задача
Реализация первого этапа учебного проекта на базе проекта Академии

### Материалы для работы
- [Дизайн](https://www.figma.com/file/SHoss54mn2SZLnI0e3OiJj/Practice?type=design&node-id=2034-1317)
- [Инструменты](https://github.com/atls/tools)
- [Библиотека компонентов](https://github.com/atls/hyperion)
- [Стартовый проект](https://github.com/atls/project-starter)

### Материалы для изучения
- [Next](https://nextjs.org/)
- [React](https://ru.reactjs.org/tutorial/tutorial.html)
- [Emotion](https://emotion.sh/docs/introduction)
- [Styled components](https://styled-components.com/)

### Реализованные проекты
- [Лендинг](https://github.com/torin-asakura/dream-team)
- [Многостраничный сайт](https://github.com/torin-asakura/misik)
- [Предоставление услуг и каталог](https://github.com/torin-asakura/shdvor)

**Comment by Nikitabkv** [comment]
**Вопрос:**
Почему такую ошибку может выдавать и куда смотреть что бы исправить?
Вебпак можно настроить через `next.config.js`, но в примерах я не видел что бы это делалось

**Лог ошибки `yarn dev`**
```
- error ../../pages/index-page/src/index.page.tsx
Module parse failed: Unexpected token (7:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|     return (
>         <h1>{text}</h1>
|     )
| }

Import trace for requested module:
../../pages/index-page/src/index.page.tsx
../../pages/index-page/src/index.ts
```

**Comment by Nikitabkv** [comment]
> **Вопрос:** Почему такую ошибку может выдавать и куда смотреть что бы исправить? Вебпак можно настроить через `next.config.js`, но в примерах я не видел что бы это делалось

Решено добавлением 
```js
module.exports = {
  experimental: {
    externalDir: true
  },
```
Где можно подробнее прочитать про остальные настройки module.exports/experimental?
В документации некста не нашел

**Comment by TorinAsakura** [comment]
> > **Вопрос:** Почему такую ошибку может выдавать и куда смотреть что бы исправить? Вебпак можно настроить через `next.config.js`, но в примерах я не видел что бы это делалось
> 
> Решено добавлением
> 
> ```js
> module.exports = {
>   experimental: {
>     externalDir: true
>   },
> ```
> 
> Где можно подробнее прочитать про остальные настройки module.exports/experimental? В документации некста не нашел

https://github.com/vercel/next.js/blob/f9795fdd2665369b60a153fbb6231f478e4a7d08/packages/next/server/config-shared.ts#L73

**Comment by Nikitabkv** [comment]
**Проблема**: Медиазапросы или что-то подобное на шаблонах компонентов

В фигме есть раздел FAQ, там 3 элемента:
 - H1
 - Кнопка
 - Вопросы
 
 
 В моём понимании надо для мобильных поменять порядок вопросов и кнопки местами, что бы шло:
 - H1
 - Вопросы
 - Кнопка
 
**Вопрос**: Где про это почитать, не нашел в документации, в примерах сайтов тоже не понял как работает адаптив

**Comment by oksssvv** [comment]
@Nikitabkv 
>В моём понимании надо для мобильных поменять порядок вопросов и кнопки местами, что бы шло:
H1
Вопросы
Кнопка

Если эту ситуацию не получается реализовать при помощи свойства `order`, задав разную очередность расположения блоков для десктопа и мобайла
То в таком случае помогает свойство `display`, оно даст возможность отобразить указанный блок для десктопа и скрыть для мобайла, ну и наоборот

**Comment by Nikitabkv** [comment]
> 
> > В моём понимании надо для мобильных поменять порядок вопросов и кнопки местами, что бы шло:
> > H1
> > Вопросы
> > Кнопка
> 
> Если эту ситуацию не получается реализовать при помощи свойства `order`, задав разную очередность расположения блоков для десктопа и мобайла То в таком случае помогает свойство `display`, оно даст возможность отобразить указанный блок для десктопа и скрыть для мобайла, ну и наоборот

Да, я понимаю как это можно сверстать, вопрос лишь в том, как это все записать в компонент, который я импортирую, где это указывать

Пример:
```jsx
<Box>
    <Text color='white'>
        Любой текст
    </Text>
</Box>
```

Как мне тут вписать условие, что бы текст был красным(или любым другим), при разрешении меньше 1000px, вот этого не могу понять

**Comment by TorinAsakura** [comment]
@Nikitabkv Используй компонент <Condition>, он есть во проектах
